export const Users = [
  {
    id:1,
    profilePicture: "assets/person/1.jpeg",
    username: "Ose Ikhalo",
  },
  {
    id:2,
    profilePicture: "assets/person/2.jpeg",
    username: "John Paul",
  },
  {
    id:3,
    profilePicture: "assets/person/3.jpeg",
    username: "Sarah Johnson",
  },
  {
    id:4,
    profilePicture: "assets/person/4.jpeg",
    username: "Erica Becky",
  },
  {
    id:5,
    profilePicture: "assets/person/5.jpeg",
    username: "Susan Jasper",
  },
  {
    id:6,
    profilePicture: "assets/person/6.jpeg",
    username: "Oliver Peter",
  },
  {
    id:7,
    profilePicture: "assets/person/7.jpeg",
    username: "Edwards Clinton",
  },
  {
    id:8,
    profilePicture: "assets/person/8.jpeg",
    username: "Maria James",
  },
  {
    id:9,
    profilePicture: "assets/person/9.jpeg",
    username: "Alli Clement",
  },
  {
    id:10,
    profilePicture: "assets/person/10.jpeg",
    username: "Mavin Newyork",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "It's always good to drink water",
    photo: "assets/post/1.jpeg",
    date: "10 mins ago",
    userId: 1,
    like: 9,
    comment: 3,
  },
  {
    id: 2,
    desc: "Read these interesting books",
    photo: "assets/post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 6,
    comment: 3,
  },
  {
    id: 3,
    desc: "It's never too late to start.",
    photo: "assets/post/3.jpeg",
    date: "30 mins ago",
    userId: 3,
    like: 11,
    comment: 6,
  },
  {
    id: 4,
    photo: "assets/post/4.jpeg",
    date: "2 hour ago",
    userId: 4,
    like: 11,
    comment: 6,
  },
  {
    id: 5,
    photo: "assets/post/5.jpeg",
    date: "3 hours ago",
    userId: 5,
    like: 20,
    comment: 15,
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    date: "6 days ago",
    userId: 6,
    like: 14,
    comment: 8,
  },
  {
    id: 7,
    desc: "Always lend a helping hand.",
    photo: "assets/post/7.jpeg",
    date: "8 days ago",
    userId: 7,
    like: 21,
    comment: 8,
  },
  {
    id: 8,
    photo: "assets/post/8.jpeg",
    date: "14 days ago",
    userId: 8,
    like: 6,
    comment: 3,
  },
  {
    id: 9,
    desc: "Never change who you are.",
    photo: "assets/post/9.jpeg",
    date: "18 days ago",
    userId: 9,
    like: 33,
    comment: 7,
  },
  {
    id: 10,
    photo: "assets/post/10.jpeg",
    date: "23 days ago",
    userId: 10,
    like: 10,
    comment: 8,
  },
];
